data = {
  "en": [
    [
      [
        "Floor covering",
        [
          [
            "Vinyl",
            [
              ""
            ],
            [
              "images/vinyl.jpg"
            ]
          ],
          [
            "Tapijt",
            [],
            [
              "images/tapijt.jpg"
            ]
          ],
          [
            "Linoleum",
            [
              ""
            ],
            [
              "images/linoleum.jpg"
            ]
          ],
          [
            "PVC",
            [
              ""
            ],
            [
              "images/pvc.jpg"
            ]
          ],
          [
            "LVT",
            [
              ""
            ],
            [
              "images/floor.jpg"
            ]
          ],
          [
            "Rubber",
            [
              ""
            ],
            [
              "images/rubber.jpg"
            ]
          ],
          [
            "Egaliseren",
            [
              ""
            ],
            [
              "images/egaliseren.jpg"
            ]
          ]
        ],
        [
          "images/floor.jpg"
        ]
      ],
      [
        "Сonstruction",
        [
          [
            "Gyproc work",
            [
              ""
            ],
            [
              "images/gyproc.jpg"
            ]
          ],
          [
            "Terrace work",
            [
              ""
            ],
            [
              "images/terrace.jpg"
            ]
          ],
          [
            "Pitched roofing",
            [
              ""
            ],
            [
              "images/roofing.jpg"
            ]
          ],
          [
            "Paintwork",
            [
              ""
            ],
            [
              "images/paint.jpg"
            ]
          ],
          [
            "Renovation",
            [
              ""
            ],
            [
              "images/renovation.jpg"
            ]
          ]
        ]
      ],
      [
        "Gallery",
        []
      ],
      [
        "Contact details",
        []
      ]
    ],
    [
      "Our partners"
    ],
    [
      "Contact"
    ],
    [
      "Let's build with GG"
    ],
    [
      "<strong>GGFloors & Construct</strong> is building a sustainable partnership.\nMore than 15 years of experience in floor coverings, but roofs no longer hold any secrets for us.\nFrom major renovations to smaller repairs as well as completely new homes.<br>\nThrough close cooperation with clients, employees and partners, we aim for the highest achievable top quality. Again and again in an open and respectful atmosphere.\nGGFloors & Construct brings your construction project to a successful conclusion.<br>\nIn this way we make life easy for the customer because we can offer the total concept.<br>\nOur greatest asset is our craftsmen, their safety and well-being is a top priority for GG construct, because this is the only way to deliver top quality to the construction site.\nDo you have construction or renovation plans:"
    ],
    [
      "images/intro.jpg"
    ],
    [
      " What are you looking for?"
    ]
  ],
  "nl": [
    [
      [
        "Vloerbekleding",
        [
          [
            "Vinyl",
            [
              ""
            ],
            [
              "images/floor.jpg"
            ]
          ],
          [
            "Tapijt",
            [
              ""
            ]
          ],
          [
            "Linoleum",
            [
              ""
            ]
          ],
          [
            "PVC",
            [
              ""
            ],
            [
              "images/floor.jpg"
            ]
          ],
          [
            "LVT",
            [
              ""
            ],
            [
              "images/floor.jpg"
            ]
          ],
          [
            "Rubber",
            [
              ""
            ],
            [
              "images/floor.jpg"
            ]
          ],
          [
            "Egaliseren",
            [
              ""
            ],
            [
              "images/floor.jpg"
            ]
          ]
        ],
        [
          "images/floor.jpg"
        ]
      ],
      [
        "Bouw",
        [
          [
            "Gyproc werk",
            [
              ""
            ],
            [
              "images/gyproc.jpg"
            ]
          ],
          [
            "Terras werk",
            [
              ""
            ],
            [
              "images/terrace.jpg"
            ]
          ],
          [
            "Hellend dakwerk",
            [
              ""
            ],
            [
              "images/roofing.jpg"
            ]
          ],
          [
            "Schilderwerk",
            [
              ""
            ],
            [
              "images/paint.jpg"
            ]
          ],
          [
            "Renovatie",
            [
              ""
            ],
            [
              "images/renovation.jpg"
            ]
          ]
        ]
      ],
      [
        "Galerie",
        []
      ],
      [
        "Contactgegevens",
        []
      ]
    ],
    [
      "Onze partners"
    ],
    [
      "Contact"
    ],
    [
      "Laten we bouwen met GG"
    ],
    [
      "<strong>GGFloors & Construct</strong> bouwt aan een duurzame partnership.<br>Al meer dan <strong>15 jaar</strong> ervaring in vloerbekledingen, maar ook daken hebben voor ons geen geheimen meer.<br> \n          Van grote renovaties tot kleinere herstellingen alsook volledige nieuwbouw woningen.<br>\n          Door een nauwe samenwerking met de opdrachtgevers, medewerkers en partners gaan we voor de hoogst haalbare topkwaliteit. Telkens weer in een open en respectvolle sfeer.<br>\n          <strong>GGFloors & Construct</strong> brengt uw bouwproject tot een goed einde.<br>\n          Zo maken we het leven van de klant makkelijk doordat wij het totaalconcept kunnen aanbieden.<br>\n          Ons grootste kapitaal, zijn onze vakmannen, hun veiligheid en welzijn is voor GG construct topprioriteit, want alleen zo kan je ook topkwaliteit afleveren op de werf.<br>\n          Heeft u bouw of verbouwplannen:"
    ],
    [
      "images/intro_nl.jpg"
    ],
    [
      "Wat zoek je?"
    ]
  ],
  "de": [
    [
      [
        "Bodenbelag",
        [
          [
            "Vinyl",
            [
              ""
            ],
            [
              "images/floor.jpg"
            ]
          ],
          [
            "Tapijt",
            [
              ""
            ]
          ],
          [
            "Linoleum",
            [
              ""
            ]
          ],
          [
            "PVC",
            [
              ""
            ],
            [
              "images/floor.jpg"
            ]
          ],
          [
            "LVT",
            [
              ""
            ],
            [
              "images/floor.jpg"
            ]
          ],
          [
            "Rubber",
            [
              ""
            ],
            [
              "images/floor.jpg"
            ]
          ],
          [
            "Egaliseren",
            [
              ""
            ],
            [
              "images/floor.jpg"
            ]
          ]
        ]
      ],
      [
        "Konstruktion",
        [
          [
            "Gyproc Arbeit"
          ],
          [
            "Terrassenarbeit"
          ],
          [
            "Pitched roofing"
          ],
          [
            "Lackierung"
          ],
          [
            "Schrägdach"
          ]
        ]
      ],
      [
        "Galerie",
        []
      ],
      [
        "Kontaktdetails",
        []
      ]
    ],
    [
      "Unsere Partner"
    ],
    [
      "Kontakt"
    ],
    [
      "Lass uns mit GG bauen"
    ],
    [
      "GGFloors & Construct baut eine nachhaltige Partnerschaft auf.\nMehr als 15 Jahre Erfahrung mit Bodenbelägen, aber Dächer bergen für uns keine Geheimnisse mehr.\nVon größeren Renovierungsarbeiten über kleinere Reparaturen bis hin zu komplett neuen Häusern.\nDurch die enge Zusammenarbeit mit Kunden, Mitarbeitern und Partnern streben wir die höchstmögliche Spitzenqualität an. Immer wieder in einer offenen und respektvollen Atmosphäre.\nGGFloors & Construct bringt Ihr Bauprojekt zu einem erfolgreichen Abschluss.\nAuf diese Weise machen wir dem Kunden das Leben leichter, weil wir das Gesamtkonzept anbieten können.\nUnser größtes Kapital sind unsere Handwerker. Ihre Sicherheit und ihr Wohlbefinden haben für GG konstruieren oberste Priorität, da dies der einzige Weg ist, um der Baustelle höchste Qualität zu liefern.\nHaben Sie Bau- oder Renovierungspläne:"
    ],
    [
      "images/intro_2.jpg"
    ],
    [
      "Was suchen Sie?"
    ]
  ],
  "fr": [
    [
      [
        "Revêtement de sol",
        [
          [
            "Vinyl",
            [
              ""
            ],
            [
              "images/floor.jpg"
            ]
          ],
          [
            "Tapijt",
            [
              ""
            ]
          ],
          [
            "Linoleum",
            [
              ""
            ]
          ],
          [
            "PVC",
            [
              ""
            ],
            [
              "images/floor.jpg"
            ]
          ],
          [
            "LVT",
            [
              ""
            ],
            [
              "images/floor.jpg"
            ]
          ],
          [
            "Rubber",
            [
              ""
            ],
            [
              "images/floor.jpg"
            ]
          ],
          [
            "Egaliseren",
            [
              ""
            ],
            [
              "images/floor.jpg"
            ]
          ]
        ]
      ],
      [
        "Construction",
        [
          [
            "Travail Gyproc"
          ],
          [
            "Travaux de terrasse"
          ],
          [
            "Toiture en pente"
          ],
          [
            "Ouvrage"
          ],
          [
            "Rénovation"
          ]
        ]
      ],
      [
        "Galerie",
        []
      ],
      [
        "Détails du contact",
        []
      ]
    ],
    [
      "Nos partenaires"
    ],
    [
      "Contacter"
    ],
    [
      "Construisons avec GG"
    ],
    [
      "GGFloors & Construct construit un partenariat durable.\nPlus de 15 ans d'expérience dans les revêtements de sol, mais les toitures n'ont plus de secret pour nous.\nDes rénovations majeures aux petites réparations en passant par les maisons complètement neuves.\nEn travaillant en étroite collaboration avec les clients, les employés et les partenaires, nous visons la meilleure qualité possible. Encore et encore dans une ambiance ouverte et respectueuse.\nGGFloors & Construct mène votre projet de construction à bonne fin.\nDe cette façon, nous facilitons la vie du client car nous pouvons offrir le concept global.\nNotre plus grande capitale est nos artisans, leur sécurité et leur bien-être sont une priorité absolue pour GG construct, car c'est le seul moyen de fournir la meilleure qualité sur le chantier.\nAvez-vous des plans de construction ou de rénovation:"
    ],
    [
      "images/intro_fr.jpg"
    ],
    [
      "Qu'est-ce que tu cherches?"
    ]
  ]
}
