const footer = document.querySelector('.footer');
const nav_yiahn = document.createElement('nav');
nav_yiahn.classList.add('footnav');
footer.appendChild(nav_yiahn);
const div_eHlht = document.createElement('div');
div_eHlht.classList.add('footnav-column');
nav_yiahn.appendChild(div_eHlht);
const h4_tMgAf = document.createElement('h4');
h4_tMgAf.classList.add('column-title');
div_eHlht.appendChild(h4_tMgAf);
h4_tMgAf.textContent += `Hoofd`;
const hr_YVtHL = document.createElement('hr');
hr_YVtHL.classList.add('title-underline');
div_eHlht.appendChild(hr_YVtHL);
const ul_XLbpz = document.createElement('ul');
div_eHlht.appendChild(ul_XLbpz);
const div_FuQNf = document.createElement('div');
div_FuQNf.classList.add('footnav-column');
nav_yiahn.appendChild(div_FuQNf);
const h4_CUnbe = document.createElement('h4');
h4_CUnbe.classList.add('column-title');
div_FuQNf.appendChild(h4_CUnbe);
h4_CUnbe.textContent += `Activiteiten`;
const hr_snsce = document.createElement('hr');
hr_snsce.classList.add('title-underline');
div_FuQNf.appendChild(hr_snsce);
const ul_zlmJt = document.createElement('ul');
div_FuQNf.appendChild(ul_zlmJt);
const div_cAtOm = document.createElement('div');
div_cAtOm.classList.add('footnav-column');
nav_yiahn.appendChild(div_cAtOm);
const h4_IVnfi = document.createElement('h4');
h4_IVnfi.classList.add('column-title');
div_cAtOm.appendChild(h4_IVnfi);
h4_IVnfi.textContent += `Socials`;
const hr_rFOEG = document.createElement('hr');
hr_rFOEG.classList.add('title-underline');
div_cAtOm.appendChild(hr_rFOEG);
const ul_ADLIH = document.createElement('ul');
div_cAtOm.appendChild(ul_ADLIH);
const li_sUsIJ = document.createElement('li');
li_sUsIJ.classList.add('footnav-link-item');
ul_ADLIH.appendChild(li_sUsIJ);
const a_EsNaW = document.createElement('a');
a_EsNaW.href = 'https://www.facebook.com/GGFloorsConstruct';
li_sUsIJ.appendChild(a_EsNaW);
a_EsNaW.textContent += `Facebook`;
const li_zXYjH = document.createElement('li');
li_zXYjH.classList.add('footnav-link-item');
ul_ADLIH.appendChild(li_zXYjH);
const a_qkqaQ = document.createElement('a');
a_qkqaQ.href = 'https://www.instagram.com/gg_floors_constructions';
li_zXYjH.appendChild(a_qkqaQ);
a_qkqaQ.textContent += `Instagram`;
const li_PPkiX = document.createElement('li');
li_PPkiX.classList.add('footnav-link-item');
ul_ADLIH.appendChild(li_PPkiX);
const a_vLzbe = document.createElement('a');
a_vLzbe.href = 'https://www.linkedin.com/company/ggvloerbekleding';
li_PPkiX.appendChild(a_vLzbe);
a_vLzbe.textContent += `Linkedin`;
const div_UZxIg = document.createElement('div');
div_UZxIg.classList.add('footnav-column', 'gegevens');
nav_yiahn.appendChild(div_UZxIg);
const h4_NBxtZ = document.createElement('h4');
h4_NBxtZ.classList.add('column-title');
div_UZxIg.appendChild(h4_NBxtZ);
h4_NBxtZ.textContent += `Gegevens:`;
const hr_BkyRr = document.createElement('hr');
hr_BkyRr.classList.add('title-underline');
div_UZxIg.appendChild(hr_BkyRr);
const ul_DVTvo = document.createElement('ul');
div_UZxIg.appendChild(ul_DVTvo);
const li_Mifmk = document.createElement('li');
li_Mifmk.classList.add('gegevens-link-item');
ul_DVTvo.appendChild(li_Mifmk);
const a_GbfGa = document.createElement('a');
a_GbfGa.href = '';
a_GbfGa.setAttribute(`target`, `_self`);
li_Mifmk.appendChild(a_GbfGa);
const span_GxOli = document.createElement('span');
span_GxOli.classList.add('ti-briefcase');
a_GbfGa.appendChild(span_GxOli);
span_GxOli.innerHTML += `&#160;`;
a_GbfGa.textContent += `GG FLOORS & CONSTRUCT bv`;
const br_rTdsZ = document.createElement('br');
a_GbfGa.appendChild(br_rTdsZ);
a_GbfGa.textContent += `BTW: BE 0704678967`;
const li_GkErs = document.createElement('li');
li_GkErs.classList.add('gegevens-link-item', 'footnav-link-item');
ul_DVTvo.appendChild(li_GkErs);
const a_MQjdp = document.createElement('a');
a_MQjdp.href = 'https://www.google.com/maps/place/GGVloerbekleding+bvba/@51.0532724,5.7378526,15z/data=!4m5!3m4!1s0x0:0xa831bc10b126f764!8m2!3d51.0532724!4d5.7378526';
a_MQjdp.setAttribute(`target`, `_self`);
li_GkErs.appendChild(a_MQjdp);
const span_mKSsa = document.createElement('span');
span_mKSsa.classList.add('ti-location-arrow');
a_MQjdp.appendChild(span_mKSsa);
span_mKSsa.innerHTML += `&#160;`;
a_MQjdp.textContent += `Kloosterpark 3, B 3650 Dilsen-Stokkem`;
const li_YWzxp = document.createElement('li');
li_YWzxp.classList.add('gegevens-link-item', 'footnav-link-item');
ul_DVTvo.appendChild(li_YWzxp);
const a_zZRql = document.createElement('a');
a_zZRql.href = 'tel:+32472815575';
a_zZRql.setAttribute(`target`, `_self`);
li_YWzxp.appendChild(a_zZRql);
const span_mgWeJ = document.createElement('span');
span_mgWeJ.classList.add('ti-mobile');
a_zZRql.appendChild(span_mgWeJ);
span_mgWeJ.innerHTML += `&#160;`;
a_zZRql.textContent += `+32472815575`;
const a_lqHDm = document.createElement('a');
a_lqHDm.href = 'mailto:ggfloorsconstruct@gmail.com';
a_lqHDm.setAttribute(`target`, `_self`);
li_YWzxp.appendChild(a_lqHDm);
const span_UxXCo = document.createElement('span');
span_UxXCo.classList.add('ti-email');
a_lqHDm.appendChild(span_UxXCo);
span_UxXCo.innerHTML += `&#160;`;
a_lqHDm.textContent += `ggfloorsconstruct@gmail.com`;
const li_lWYLq = document.createElement('li');
li_lWYLq.classList.add('gegevens-link-item');
ul_DVTvo.appendChild(li_lWYLq);
const a_rlzqw = document.createElement('a');
a_rlzqw.href = '';
a_rlzqw.setAttribute(`target`, `_self`);
li_lWYLq.appendChild(a_rlzqw);
const span_KkpRp = document.createElement('span');
span_KkpRp.classList.add('ti-wallet');
a_rlzqw.appendChild(span_KkpRp);
span_KkpRp.innerHTML += `&#160;`;
a_rlzqw.textContent += `BNP PARIBAS/Fortis`;
const br_XxNKi = document.createElement('br');
a_rlzqw.appendChild(br_XxNKi);
a_rlzqw.textContent += `BE71 0019 0088 6869`;
const img_pOYbM = new Image();
img_pOYbM.classList.add('footer-logo');
img_pOYbM.style.margin = '20px auto';
img_pOYbM.style.display = 'block';
img_pOYbM.setAttribute(`width`, `40`);
img_pOYbM.src = 'images/logo.svg';
img_pOYbM.setAttribute(`alt`, `GG Floors and Construct`);
div_UZxIg.appendChild(img_pOYbM);
const div_jkKHb = document.createElement('div');
div_jkKHb.classList.add('basement');
footer.appendChild(div_jkKHb);
const div_AoYCw = document.createElement('div');
div_AoYCw.classList.add('copyright');
div_jkKHb.appendChild(div_AoYCw);
const span_VRVLK = document.createElement('span');
span_VRVLK.classList.add('copyright-title');
div_AoYCw.appendChild(span_VRVLK);
span_VRVLK.textContent += `GG Floors & Construct 2021 ©`;
const ul_iWqoA = document.createElement('ul');
ul_iWqoA.classList.add('items-list-inline');
div_AoYCw.appendChild(ul_iWqoA);
const li_boiyO = document.createElement('li');
ul_iWqoA.appendChild(li_boiyO);
const a_KuXaU = document.createElement('a');
a_KuXaU.setAttribute(`target`, `blink`);
a_KuXaU.href = 'files/maatschappelijke-zetel.pdf';
li_boiyO.appendChild(a_KuXaU);
const span_tKhRS = document.createElement('span');
a_KuXaU.appendChild(span_tKhRS);
span_tKhRS.textContent += `Maatschappelijke Zetel`;
const li_bShHv = document.createElement('li');
ul_iWqoA.appendChild(li_bShHv);
const a_XHnxy = document.createElement('a');
a_XHnxy.setAttribute(`target`, `blink`);
a_XHnxy.href = 'files/rubriek-oprichting.pdf';
li_bShHv.appendChild(a_XHnxy);
const span_ZdLMk = document.createElement('span');
a_XHnxy.appendChild(span_ZdLMk);
span_ZdLMk.textContent += `Rubriek Oprichting`;
const li_nwQuV = document.createElement('li');
ul_iWqoA.appendChild(li_nwQuV);
const a_uNjIL = document.createElement('a');
a_uNjIL.setAttribute(`target`, `blink`);
a_uNjIL.href = 'files/financiele-gegevens.pdf';
li_nwQuV.appendChild(a_uNjIL);
const span_GMiin = document.createElement('span');
a_uNjIL.appendChild(span_GMiin);
span_GMiin.textContent += `Financiële Gegevens`;
const div_XyScq = document.createElement('div');
div_XyScq.classList.add('socials');
div_jkKHb.appendChild(div_XyScq);
const ul_csLXc = document.createElement('ul');
div_XyScq.appendChild(ul_csLXc);
const li_krpZI = document.createElement('li');
ul_csLXc.appendChild(li_krpZI);
const a_MYalv = document.createElement('a');
a_MYalv.classList.add('ti-facebook');
a_MYalv.href = 'https://www.facebook.com/GGFloorsConstruct';
li_krpZI.appendChild(a_MYalv);
const li_QVMRi = document.createElement('li');
ul_csLXc.appendChild(li_QVMRi);
const a_yoDfW = document.createElement('a');
a_yoDfW.classList.add('ti-linkedin');
a_yoDfW.href = 'https://www.linkedin.com/company/ggvloerbekleding';
li_QVMRi.appendChild(a_yoDfW);
const li_ifDPm = document.createElement('li');
ul_csLXc.appendChild(li_ifDPm);
const a_BAVIH = document.createElement('a');
a_BAVIH.classList.add('ti-instagram');
a_BAVIH.href = 'https://www.instagram.com/gg_floors_constructions';
li_ifDPm.appendChild(a_BAVIH);
const div_IQyog = document.createElement('div');
div_IQyog.classList.add('contact-widget');
footer.appendChild(div_IQyog);
const input_rpkdF = document.createElement('input');
input_rpkdF.classList.add('contact-widget-input');
input_rpkdF.setAttribute(`type`, `checkbox`);
div_IQyog.appendChild(input_rpkdF);
const button_hqlQG = document.createElement('button');
button_hqlQG.classList.add('contact-widget-btn', 'ti-comment');
div_IQyog.appendChild(button_hqlQG);
const div_PdaqZ = document.createElement('div');
div_PdaqZ.classList.add('contact-widget-container');
div_IQyog.appendChild(div_PdaqZ);
const ul_JgRLS = document.createElement('ul');
ul_JgRLS.classList.add('items-of-contact');
div_PdaqZ.appendChild(ul_JgRLS);
const li_dMRgc = document.createElement('li');
li_dMRgc.classList.add('item-phone');
ul_JgRLS.appendChild(li_dMRgc);
const a_eVUxo = document.createElement('a');
a_eVUxo.classList.add('ti-mobile');
a_eVUxo.href = 'contact.html';
a_eVUxo.setAttribute(`title`, `Contact`);
li_dMRgc.appendChild(a_eVUxo);
const li_FEVuP = document.createElement('li');
li_FEVuP.classList.add('item-mail');
ul_JgRLS.appendChild(li_FEVuP);
const a_uCuFu = document.createElement('a');
a_uCuFu.classList.add('ti-email');
a_uCuFu.href = 'mailto:ggfloorsconstruct@gmail.com';
a_uCuFu.setAttribute(`title`, `E-mail`);
li_FEVuP.appendChild(a_uCuFu);
const li_VFVue = document.createElement('li');
li_VFVue.classList.add('item-form');
ul_JgRLS.appendChild(li_VFVue);
const a_QYGet = document.createElement('a');
a_QYGet.classList.add('ti-view-list-alt');
a_QYGet.href = 'form.html';
a_QYGet.setAttribute(`title`, `Form`);
li_VFVue.appendChild(a_QYGet);
const div_fLsVJ = document.createElement('div');
div_fLsVJ.classList.add('chat-to');
div_IQyog.appendChild(div_fLsVJ);
const p_gMpFZ = document.createElement('p');
div_fLsVJ.appendChild(p_gMpFZ);
p_gMpFZ.textContent += `Contact us`;
