const header = document.querySelector('.header');
const div_wWKlq = document.createElement('div');
div_wWKlq.classList.add('topbar');
header.appendChild(div_wWKlq);
const div_YcNnX = document.createElement('div');
div_YcNnX.classList.add('flex-container');
div_wWKlq.appendChild(div_YcNnX);
const div_PfUyx = document.createElement('div');
div_PfUyx.classList.add('dropdown-list', 'partners-list');
div_YcNnX.appendChild(div_PfUyx);
const div_WOUCR = document.createElement('div');
div_WOUCR.classList.add('dropdown-select');
div_PfUyx.appendChild(div_WOUCR);
const div_VBsJS = document.createElement('div');
div_VBsJS.classList.add('dropdown-title', 'partners');
div_WOUCR.appendChild(div_VBsJS);
const span_fHYHq = document.createElement('span');
div_VBsJS.appendChild(span_fHYHq);
span_fHYHq.textContent += `Onze partners`;
const div_rmFHW = document.createElement('div');
div_rmFHW.classList.add('arrow');
div_VBsJS.appendChild(div_rmFHW);
const div_xAiyz = document.createElement('div');
div_xAiyz.classList.add('options');
div_WOUCR.appendChild(div_xAiyz);
const a_ejGhh = document.createElement('a');
a_ejGhh.classList.add('option');
a_ejGhh.href = 'https://www.uzin.com';
a_ejGhh.setAttribute(`target`, `blink`);
div_xAiyz.appendChild(a_ejGhh);
const img_abtxE = new Image();
img_abtxE.src = 'images/logos/partners/uzin-logo.png';
img_abtxE.setAttribute(`alt`, `uzin utz`);
img_abtxE.setAttribute(`title`, `Uzin Utz`);
a_ejGhh.appendChild(img_abtxE);
const a_EBxvQ = document.createElement('a');
a_EBxvQ.classList.add('option');
a_EBxvQ.href = 'https://www.knauf.com';
a_EBxvQ.setAttribute(`target`, `blink`);
div_xAiyz.appendChild(a_EBxvQ);
const img_Sekoh = new Image();
img_Sekoh.src = 'images/logos/partners/knauf-logo.png';
img_Sekoh.setAttribute(`alt`, `knauf`);
img_Sekoh.setAttribute(`title`, `Knauf`);
a_EBxvQ.appendChild(img_Sekoh);
const a_TDttL = document.createElement('a');
a_TDttL.classList.add('option');
a_TDttL.href = 'https://www.forbo.com';
a_TDttL.setAttribute(`target`, `blink`);
div_xAiyz.appendChild(a_TDttL);
const img_hijZT = new Image();
img_hijZT.src = 'images/logos/partners/forbo-logo.png';
img_hijZT.setAttribute(`alt`, `forbo`);
img_hijZT.setAttribute(`title`, `Forbo`);
a_TDttL.appendChild(img_hijZT);
const a_IQWXE = document.createElement('a');
a_IQWXE.classList.add('option');
a_IQWXE.href = 'https://www.perfecty.be';
a_IQWXE.setAttribute(`target`, `blink`);
div_xAiyz.appendChild(a_IQWXE);
const img_RDXPM = new Image();
img_RDXPM.src = 'images/logos/partners/perfecty-logo.png';
img_RDXPM.setAttribute(`alt`, `perfecty`);
img_RDXPM.setAttribute(`title`, `Perfecty`);
a_IQWXE.appendChild(img_RDXPM);
const a_oVynT = document.createElement('a');
a_oVynT.classList.add('option');
a_oVynT.href = 'https://www.campaert.be';
a_oVynT.setAttribute(`target`, `blink`);
div_xAiyz.appendChild(a_oVynT);
const img_bXjlZ = new Image();
img_bXjlZ.src = 'images/logos/partners/campaert-logo.png';
img_bXjlZ.setAttribute(`alt`, `campaert`);
img_bXjlZ.setAttribute(`title`, `Campaert`);
a_oVynT.appendChild(img_bXjlZ);
const a_MCYBq = document.createElement('a');
a_MCYBq.classList.add('option');
a_MCYBq.href = 'https://www.exclusivedecor.nl';
a_MCYBq.setAttribute(`target`, `blink`);
div_xAiyz.appendChild(a_MCYBq);
const img_XtQFa = new Image();
img_XtQFa.src = 'images/logos/partners/exclusive-logo.png';
img_XtQFa.setAttribute(`alt`, `exclusive`);
img_XtQFa.setAttribute(`title`, `Exclusive`);
a_MCYBq.appendChild(img_XtQFa);
const a_eyTqN = document.createElement('a');
a_eyTqN.classList.add('option');
a_eyTqN.href = 'https://www.grupa-wolff.eu';
a_eyTqN.setAttribute(`target`, `blink`);
div_xAiyz.appendChild(a_eyTqN);
const img_Bvbvb = new Image();
img_Bvbvb.style.borderRadius = '4px';
img_Bvbvb.style.background = '#ddd';
img_Bvbvb.src = 'images/logos/partners/wolff-logo.png';
img_Bvbvb.setAttribute(`alt`, `Wolff`);
img_Bvbvb.setAttribute(`title`, `Wolff`);
a_eyTqN.appendChild(img_Bvbvb);
const a_UljZu = document.createElement('a');
a_UljZu.classList.add('option');
a_UljZu.href = 'https://https://www.pspprojects.com/';
a_UljZu.setAttribute(`target`, `blink`);
div_xAiyz.appendChild(a_UljZu);
const img_UjbEv = new Image();
img_UjbEv.src = 'images/logos/partners/psp-logo.png';
img_UjbEv.setAttribute(`alt`, `psp`);
img_UjbEv.setAttribute(`title`, `PSP`);
a_UljZu.appendChild(img_UjbEv);
const a_qSAhv = document.createElement('a');
a_qSAhv.classList.add('option');
a_qSAhv.href = 'https://www.generalfloor.com';
a_qSAhv.setAttribute(`target`, `blink`);
div_xAiyz.appendChild(a_qSAhv);
const img_msrzi = new Image();
img_msrzi.src = 'images/logos/partners/general-floor-logo.png';
img_msrzi.setAttribute(`alt`, `general-floor`);
img_msrzi.setAttribute(`title`, `General-floor`);
a_qSAhv.appendChild(img_msrzi);
const a_JaOya = document.createElement('a');
a_JaOya.classList.add('option');
a_JaOya.href = 'https://www.bouwpuntdeckers.be';
a_JaOya.setAttribute(`target`, `blink`);
div_xAiyz.appendChild(a_JaOya);
const img_bUkPT = new Image();
img_bUkPT.src = 'images/logos/partners/bouwpuntdeckers.png';
img_bUkPT.setAttribute(`alt`, `bouwpuntdeckers`);
img_bUkPT.setAttribute(`title`, `Bouwpunt Deckers`);
a_JaOya.appendChild(img_bUkPT);
const span_zBDnu = document.createElement('span');
span_zBDnu.classList.add('separator');
div_YcNnX.appendChild(span_zBDnu);
const a_DqQRj = document.createElement('a');
a_DqQRj.classList.add('topbar-contact-link');
a_DqQRj.href = 'form.html';
div_YcNnX.appendChild(a_DqQRj);
a_DqQRj.textContent += `Contact`;
const div_NtMrn = document.createElement('div');
div_NtMrn.classList.add('flex-container');
div_wWKlq.appendChild(div_NtMrn);
const div_yPRHg = document.createElement('div');
div_yPRHg.classList.add('socials');
div_NtMrn.appendChild(div_yPRHg);
const ul_eICCl = document.createElement('ul');
div_yPRHg.appendChild(ul_eICCl);
const li_cIPge = document.createElement('li');
ul_eICCl.appendChild(li_cIPge);
const a_fQWWi = document.createElement('a');
a_fQWWi.classList.add('ti-facebook');
a_fQWWi.href = 'https://www.facebook.com/GGFloorsConstruct';
li_cIPge.appendChild(a_fQWWi);
const li_qwvnM = document.createElement('li');
ul_eICCl.appendChild(li_qwvnM);
const a_HDYyo = document.createElement('a');
a_HDYyo.classList.add('ti-linkedin');
a_HDYyo.href = 'https://www.linkedin.com/company/ggvloerbekleding';
li_qwvnM.appendChild(a_HDYyo);
const li_oRnZW = document.createElement('li');
ul_eICCl.appendChild(li_oRnZW);
const a_cOFvH = document.createElement('a');
a_cOFvH.classList.add('ti-instagram');
a_cOFvH.href = 'https://www.instagram.com/gg_floors_constructions';
li_oRnZW.appendChild(a_cOFvH);
const div_WHGHI = document.createElement('div');
div_WHGHI.classList.add('dropdown-list', 'available-languages');
div_NtMrn.appendChild(div_WHGHI);
const div_dwMxO = document.createElement('div');
div_dwMxO.classList.add('dropdown-select');
div_WHGHI.appendChild(div_dwMxO);
const div_VyADg = document.createElement('div');
div_VyADg.classList.add('dropdown-title', 'current-lang');
div_dwMxO.appendChild(div_VyADg);
const span_gjZQq = document.createElement('span');
div_VyADg.appendChild(span_gjZQq);
span_gjZQq.textContent += `NL`;
const div_pumLj = document.createElement('div');
div_pumLj.classList.add('arrow');
div_VyADg.appendChild(div_pumLj);
const ul_lXcWI = document.createElement('ul');
ul_lXcWI.classList.add('options', 'options-lang');
div_dwMxO.appendChild(ul_lXcWI);
const li_RapCf = document.createElement('li');
li_RapCf.classList.add('option', 'selected');
ul_lXcWI.appendChild(li_RapCf);
const a_HofcW = document.createElement('a');
a_HofcW.href = '#nl';
li_RapCf.appendChild(a_HofcW);
a_HofcW.textContent += `NL`;
const li_hzYnE = document.createElement('li');
li_hzYnE.classList.add('option');
ul_lXcWI.appendChild(li_hzYnE);
const a_NdnSp = document.createElement('a');
a_NdnSp.href = '#en';
li_hzYnE.appendChild(a_NdnSp);
a_NdnSp.textContent += `EN`;
const li_kAdHW = document.createElement('li');
li_kAdHW.classList.add('option');
ul_lXcWI.appendChild(li_kAdHW);
const a_KUMZL = document.createElement('a');
a_KUMZL.href = '#de';
li_kAdHW.appendChild(a_KUMZL);
a_KUMZL.textContent += `DE`;
const li_lBsgc = document.createElement('li');
li_lBsgc.classList.add('option');
ul_lXcWI.appendChild(li_lBsgc);
const a_EXEha = document.createElement('a');
a_EXEha.href = '#fr';
li_lBsgc.appendChild(a_EXEha);
a_EXEha.textContent += `FR`;
const div_FLaGF = document.createElement('div');
div_FLaGF.classList.add('navbar');
header.appendChild(div_FLaGF);
const div_NNNYC = document.createElement('div');
div_NNNYC.classList.add('header-logo');
div_FLaGF.appendChild(div_NNNYC);
const a_MDKSA = document.createElement('a');
a_MDKSA.classList.add('link-to-home');
a_MDKSA.href = 'https://ggfloors-construct.be';
a_MDKSA.setAttribute(`target`, `_blank`);
a_MDKSA.setAttribute(`rel`, `noopener`);
a_MDKSA.setAttribute(`title`, `GG FLOORS & CONSTRUCT | Home page`);
div_NNNYC.appendChild(a_MDKSA);
const div_OVMIC = document.createElement('div');
div_OVMIC.classList.add('header-logo-image');
a_MDKSA.appendChild(div_OVMIC);
const img_PcUkZ = new Image();
img_PcUkZ.src = 'images/logos/logo.svg';
img_PcUkZ.setAttribute(`alt`, `gg-construct logo`);
div_OVMIC.appendChild(img_PcUkZ);
const span_SYYfu = document.createElement('span');
span_SYYfu.classList.add('logo-title');
a_MDKSA.appendChild(span_SYYfu);
span_SYYfu.textContent += `GG FLOORS & CONSTRUCT`;
const nav_QjVlV = document.createElement('nav');
nav_QjVlV.classList.add('topnav');
div_FLaGF.appendChild(nav_QjVlV);
const ul_hUyrY = document.createElement('ul');
nav_QjVlV.appendChild(ul_hUyrY);
const li_OXJmb = document.createElement('li');
li_OXJmb.classList.add('topnav-item');
ul_hUyrY.appendChild(li_OXJmb);
const a_wacDA = document.createElement('a');
a_wacDA.classList.add('parent-link');
a_wacDA.href = 'home.html';
li_OXJmb.appendChild(a_wacDA);
a_wacDA.textContent += `Home`;
const li_rlrBI = document.createElement('li');
li_rlrBI.classList.add('topnav-item');
ul_hUyrY.appendChild(li_rlrBI);
const a_dCaXf = document.createElement('a');
a_dCaXf.classList.add('parent-link');
a_dCaXf.href = '';
li_rlrBI.appendChild(a_dCaXf);
a_dCaXf.textContent += `Over ons`;
const li_SwIRf = document.createElement('li');
li_SwIRf.classList.add('topnav-item', 'parent');
ul_hUyrY.appendChild(li_SwIRf);
const a_EHJrQ = document.createElement('a');
a_EHJrQ.classList.add('parent-link');
a_EHJrQ.href = '';
li_SwIRf.appendChild(a_EHJrQ);
a_EHJrQ.textContent += `Activiteiten`;
const ul_hcqEy = document.createElement('ul');
ul_hcqEy.classList.add('topnav-dropdown-column');
li_SwIRf.appendChild(ul_hcqEy);
const li_aMvZb = document.createElement('li');
ul_hcqEy.appendChild(li_aMvZb);
const a_aumDq = document.createElement('a');
a_aumDq.href = '';
li_aMvZb.appendChild(a_aumDq);
a_aumDq.textContent += `Vloerder`;
const li_swQrL = document.createElement('li');
ul_hcqEy.appendChild(li_swQrL);
const a_fBFxH = document.createElement('a');
a_fBFxH.href = '';
li_swQrL.appendChild(a_fBFxH);
a_fBFxH.textContent += `Schilderwerken`;
const li_SciMV = document.createElement('li');
ul_hcqEy.appendChild(li_SciMV);
const a_YsnpK = document.createElement('a');
a_YsnpK.href = '';
li_SciMV.appendChild(a_YsnpK);
a_YsnpK.textContent += `Gyprocwerken`;
const li_DODyv = document.createElement('li');
ul_hcqEy.appendChild(li_DODyv);
const a_vMNjb = document.createElement('a');
a_vMNjb.href = '';
li_DODyv.appendChild(a_vMNjb);
a_vMNjb.textContent += `Pleisterwerken`;
const li_BCEyA = document.createElement('li');
ul_hcqEy.appendChild(li_BCEyA);
const a_EiKma = document.createElement('a');
a_EiKma.href = '';
li_BCEyA.appendChild(a_EiKma);
a_EiKma.textContent += `Terrassen en opritten`;
const li_Uopsa = document.createElement('li');
ul_hcqEy.appendChild(li_Uopsa);
const a_OUkcS = document.createElement('a');
a_OUkcS.href = '';
li_Uopsa.appendChild(a_OUkcS);
a_OUkcS.textContent += `Dakwerken`;
const li_dSBde = document.createElement('li');
ul_hcqEy.appendChild(li_dSBde);
const a_bNtgp = document.createElement('a');
a_bNtgp.href = '';
li_dSBde.appendChild(a_bNtgp);
a_bNtgp.textContent += `Gevels`;
const li_zuyhE = document.createElement('li');
ul_hcqEy.appendChild(li_zuyhE);
const a_gnIfM = document.createElement('a');
a_gnIfM.href = '';
li_zuyhE.appendChild(a_gnIfM);
a_gnIfM.textContent += `Renovatie`;
const li_FMKzn = document.createElement('li');
ul_hcqEy.appendChild(li_FMKzn);
const a_niynD = document.createElement('a');
a_niynD.href = '';
li_FMKzn.appendChild(a_niynD);
a_niynD.textContent += `Nieuwbouw`;
const li_jkdtW = document.createElement('li');
ul_hcqEy.appendChild(li_jkdtW);
const a_gOAFx = document.createElement('a');
a_gOAFx.classList.add('more', 'topnav-dropdown-item');
a_gOAFx.href = 'activiteiten.html';
li_jkdtW.appendChild(a_gOAFx);
a_gOAFx.textContent += `...`;
const li_aQlgh = document.createElement('li');
li_aQlgh.classList.add('topnav-item');
ul_hUyrY.appendChild(li_aQlgh);
const a_DkIor = document.createElement('a');
a_DkIor.classList.add('parent-link');
a_DkIor.href = '';
li_aQlgh.appendChild(a_DkIor);
a_DkIor.textContent += `Referenties`;
const li_iFCTd = document.createElement('li');
li_iFCTd.classList.add('topnav-item');
ul_hUyrY.appendChild(li_iFCTd);
const a_rJEdX = document.createElement('a');
a_rJEdX.classList.add('parent-link');
a_rJEdX.href = '';
li_iFCTd.appendChild(a_rJEdX);
a_rJEdX.textContent += `Nieuws`;
const li_NbKCY = document.createElement('li');
li_NbKCY.classList.add('topnav-item');
ul_hUyrY.appendChild(li_NbKCY);
const a_rkNdV = document.createElement('a');
a_rkNdV.classList.add('parent-link');
a_rkNdV.href = '';
li_NbKCY.appendChild(a_rkNdV);
a_rkNdV.textContent += `Vacatures`;
const li_iguxn = document.createElement('li');
li_iguxn.classList.add('topnav-item');
ul_hUyrY.appendChild(li_iguxn);
const a_FXdKb = document.createElement('a');
a_FXdKb.classList.add('parent-link');
a_FXdKb.href = 'contact.html';
li_iguxn.appendChild(a_FXdKb);
a_FXdKb.textContent += `Contact`;
const div_HaQVF = document.createElement('div');
div_HaQVF.classList.add('topnav-btns');
nav_QjVlV.appendChild(div_HaQVF);
const a_tAIBK = document.createElement('a');
a_tAIBK.classList.add('btn', 'btn-default', 'btn-call');
a_tAIBK.href = 'tel:+32472815575';
div_HaQVF.appendChild(a_tAIBK);
const img_dTNRZ = new Image();
img_dTNRZ.src = 'images/icons/phone-call.svg';
img_dTNRZ.setAttribute(`alt`, `phone`);
a_tAIBK.appendChild(img_dTNRZ);
const img_SuhbB = new Image();
img_SuhbB.src = 'images/icons/dial-pad.svg';
img_SuhbB.setAttribute(`alt`, `dial-pad`);
a_tAIBK.appendChild(img_SuhbB);
const button_lPXLu = document.createElement('button');
button_lPXLu.classList.add('btn', 'btn-search', 'ti-search');
div_HaQVF.appendChild(button_lPXLu);
const div_tIIXf = document.createElement('div');
div_tIIXf.id = 'menuToggle';
header.appendChild(div_tIIXf);
const input_HzJvt = document.createElement('input');
input_HzJvt.setAttribute(`type`, `checkbox`);
div_tIIXf.appendChild(input_HzJvt);
const span_UsqZD = document.createElement('span');
div_tIIXf.appendChild(span_UsqZD);
const span_ctJyD = document.createElement('span');
div_tIIXf.appendChild(span_ctJyD);
const span_BNKdM = document.createElement('span');
div_tIIXf.appendChild(span_BNKdM);
const ul_YMKVb = document.createElement('ul');
ul_YMKVb.classList.add('mobile-dropdown-column');
div_tIIXf.appendChild(ul_YMKVb);
const div_qdYMt = document.createElement('div');
div_qdYMt.classList.add('search');
header.appendChild(div_qdYMt);
const div_lpRMx = document.createElement('div');
div_lpRMx.classList.add('search-modal');
div_qdYMt.appendChild(div_lpRMx);
const div_MUFAM = document.createElement('div');
div_MUFAM.classList.add('search_container');
div_lpRMx.appendChild(div_MUFAM);
const div_tZPFJ = document.createElement('div');
div_tZPFJ.classList.add('search_intro-placeholder');
div_MUFAM.appendChild(div_tZPFJ);
const div_iMEqS = document.createElement('div');
div_iMEqS.classList.add('search_intro');
div_tZPFJ.appendChild(div_iMEqS);
div_iMEqS.textContent += `What are you looking for?`;
const form_aOeIi = document.createElement('form');
form_aOeIi.id = 'formMenuSearch';
form_aOeIi.setAttribute(`name`, `query`);
form_aOeIi.setAttribute(`action`, ``);
form_aOeIi.setAttribute(`method`, `GET`);
div_MUFAM.appendChild(form_aOeIi);
const div_IonOF = document.createElement('div');
div_IonOF.classList.add('search_input');
form_aOeIi.appendChild(div_IonOF);
const div_cDnjQ = document.createElement('div');
div_cDnjQ.classList.add('search-wrapper');
div_IonOF.appendChild(div_cDnjQ);
const input_CgXDq = document.createElement('input');
input_CgXDq.classList.add('search-box');
input_CgXDq.setAttribute(`type`, `search`);
input_CgXDq.setAttribute(`placeholder`, `Plaster`);
input_CgXDq.setAttribute('autofocus', '');
div_cDnjQ.appendChild(input_CgXDq);
const div_HgkLD = document.createElement('div');
div_HgkLD.classList.add('search_submit');
div_IonOF.appendChild(div_HgkLD);
const button_YeRLN = document.createElement('button');
button_YeRLN.classList.add('btn-default');
button_YeRLN.setAttribute(`type`, `submit`);
div_HgkLD.appendChild(button_YeRLN);
const img_dZkbO = new Image();
img_dZkbO.src = 'images/icons/loupe.svg';
img_dZkbO.setAttribute(`alt`, `search`);
button_YeRLN.appendChild(img_dZkbO);
const div_xTLTk = document.createElement('div');
div_xTLTk.classList.add('search_placeholder-suggestions');
div_lpRMx.appendChild(div_xTLTk);
const div_QyXJH = document.createElement('div');
div_QyXJH.classList.add('search_wrapper-suggestions');
div_xTLTk.appendChild(div_QyXJH);
const span_bovte = document.createElement('span');
div_QyXJH.appendChild(span_bovte);
const ul_emnXj = document.createElement('ul');
ul_emnXj.classList.add('search_list-suggestions');
div_QyXJH.appendChild(ul_emnXj);
const li_mJdwx = document.createElement('li');
ul_emnXj.appendChild(li_mJdwx);
const a_qravQ = document.createElement('a');
a_qravQ.classList.add('search_link');
a_qravQ.href = 'activiteiten.html';
li_mJdwx.appendChild(a_qravQ);
a_qravQ.textContent += `Plaster`;
const span_VTLBx = document.createElement('span');
li_mJdwx.appendChild(span_VTLBx);
span_VTLBx.textContent += `|`;
const li_rnZjW = document.createElement('li');
ul_emnXj.appendChild(li_rnZjW);
const a_vdTIz = document.createElement('a');
a_vdTIz.classList.add('search_link');
a_vdTIz.href = 'activiteiten.html';
li_rnZjW.appendChild(a_vdTIz);
a_vdTIz.textContent += `Ground`;
const span_mHfwC = document.createElement('span');
li_rnZjW.appendChild(span_mHfwC);
span_mHfwC.textContent += `|`;
const li_nDbnf = document.createElement('li');
ul_emnXj.appendChild(li_nDbnf);
const a_tigmn = document.createElement('a');
a_tigmn.classList.add('search_link');
a_tigmn.href = 'activiteiten.html';
li_nDbnf.appendChild(a_tigmn);
a_tigmn.textContent += `Walls`;
const span_JgAas = document.createElement('span');
li_nDbnf.appendChild(span_JgAas);
span_JgAas.textContent += `|`;
const li_myjfH = document.createElement('li');
ul_emnXj.appendChild(li_myjfH);
const a_LRfyP = document.createElement('a');
a_LRfyP.classList.add('search_link');
a_LRfyP.href = 'activiteiten.html';
li_myjfH.appendChild(a_LRfyP);
a_LRfyP.textContent += `Paint`;
