const header = document.querySelector('.header');
const div_wWKlq = document.createElement('div');
div_wWKlq.classList.add('topbar');
header.appendChild(div_wWKlq);
const div_YcNnX = document.createElement('div');
div_YcNnX.classList.add('flex-container');
div_wWKlq.appendChild(div_YcNnX);
const div_PfUyx = document.createElement('div');
div_PfUyx.classList.add('dropdown-list', 'partners-list');
div_YcNnX.appendChild(div_PfUyx);
const div_WOUCR = document.createElement('div');
div_WOUCR.classList.add('dropdown-select');
div_PfUyx.appendChild(div_WOUCR);
const div_VBsJS = document.createElement('div');
div_VBsJS.classList.add('dropdown-title', 'partners');
div_WOUCR.appendChild(div_VBsJS);
const span_fHYHq = document.createElement('span');
div_VBsJS.appendChild(span_fHYHq);
span_fHYHq.textContent += `Onze partners`;
const div_rmFHW = document.createElement('div');
div_rmFHW.classList.add('arrow');
div_VBsJS.appendChild(div_rmFHW);
const div_xAiyz = document.createElement('div');
div_xAiyz.classList.add('options');
div_WOUCR.appendChild(div_xAiyz);
const a_ejGhh = document.createElement('a');
a_ejGhh.classList.add('option');
a_ejGhh.href = 'https://www.uzin.com';
a_ejGhh.setAttribute(`target`, `blink`);
div_xAiyz.appendChild(a_ejGhh);
const img_abtxE = new Image();
img_abtxE.src = 'images/logos/partners/uzin-logo.png';
img_abtxE.setAttribute(`alt`, `uzin utz`);
img_abtxE.setAttribute(`title`, `Uzin Utz`);
a_ejGhh.appendChild(img_abtxE);
const a_EBxvQ = document.createElement('a');
a_EBxvQ.classList.add('option');
a_EBxvQ.href = 'https://www.knauf.com';
a_EBxvQ.setAttribute(`target`, `blink`);
div_xAiyz.appendChild(a_EBxvQ);
const img_Sekoh = new Image();
img_Sekoh.src = 'images/logos/partners/knauf-logo.png';
img_Sekoh.setAttribute(`alt`, `knauf`);
img_Sekoh.setAttribute(`title`, `Knauf`);
a_EBxvQ.appendChild(img_Sekoh);
const a_TDttL = document.createElement('a');
a_TDttL.classList.add('option');
a_TDttL.href = 'https://www.forbo.com';
a_TDttL.setAttribute(`target`, `blink`);
div_xAiyz.appendChild(a_TDttL);
const img_hijZT = new Image();
img_hijZT.src = 'images/logos/partners/forbo-logo.png';
img_hijZT.setAttribute(`alt`, `forbo`);
img_hijZT.setAttribute(`title`, `Forbo`);
a_TDttL.appendChild(img_hijZT);
const a_IQWXE = document.createElement('a');
a_IQWXE.classList.add('option');
a_IQWXE.href = 'https://www.perfecty.be';
a_IQWXE.setAttribute(`target`, `blink`);
div_xAiyz.appendChild(a_IQWXE);
const img_RDXPM = new Image();
img_RDXPM.src = 'images/logos/partners/perfecty-logo.png';
img_RDXPM.setAttribute(`alt`, `perfecty`);
img_RDXPM.setAttribute(`title`, `Perfecty`);
a_IQWXE.appendChild(img_RDXPM);
const a_oVynT = document.createElement('a');
a_oVynT.classList.add('option');
a_oVynT.href = 'https://www.campaert.be';
a_oVynT.setAttribute(`target`, `blink`);
div_xAiyz.appendChild(a_oVynT);
const img_bXjlZ = new Image();
img_bXjlZ.src = 'images/logos/partners/campaert-logo.png';
img_bXjlZ.setAttribute(`alt`, `campaert`);
img_bXjlZ.setAttribute(`title`, `Campaert`);
a_oVynT.appendChild(img_bXjlZ);
const a_MCYBq = document.createElement('a');
a_MCYBq.classList.add('option');
a_MCYBq.href = 'https://www.exclusivedecor.nl';
a_MCYBq.setAttribute(`target`, `blink`);
div_xAiyz.appendChild(a_MCYBq);
const img_XtQFa = new Image();
img_XtQFa.src = 'images/logos/partners/exclusive-logo.png';
img_XtQFa.setAttribute(`alt`, `exclusive`);
img_XtQFa.setAttribute(`title`, `Exclusive`);
a_MCYBq.appendChild(img_XtQFa);
const a_eyTqN = document.createElement('a');
a_eyTqN.classList.add('option');
a_eyTqN.href = 'https://www.grupa-wolff.eu';
a_eyTqN.setAttribute(`target`, `blink`);
div_xAiyz.appendChild(a_eyTqN);
const img_Bvbvb = new Image();
img_Bvbvb.style.borderRadius = '4px';
img_Bvbvb.style.background = '#ddd';
img_Bvbvb.src = 'images/logos/partners/wolff-logo.png';
img_Bvbvb.setAttribute(`alt`, `Wolff`);
img_Bvbvb.setAttribute(`title`, `Wolff`);
a_eyTqN.appendChild(img_Bvbvb);
const a_UljZu = document.createElement('a');
a_UljZu.classList.add('option');
a_UljZu.href = 'https://https://www.pspprojects.com/';
a_UljZu.setAttribute(`target`, `blink`);
div_xAiyz.appendChild(a_UljZu);
const img_UjbEv = new Image();
img_UjbEv.src = 'images/logos/partners/psp-logo.png';
img_UjbEv.setAttribute(`alt`, `psp`);
img_UjbEv.setAttribute(`title`, `PSP`);
a_UljZu.appendChild(img_UjbEv);
const a_qSAhv = document.createElement('a');
a_qSAhv.classList.add('option');
a_qSAhv.href = 'https://www.generalfloor.com';
a_qSAhv.setAttribute(`target`, `blink`);
div_xAiyz.appendChild(a_qSAhv);
const img_msrzi = new Image();
img_msrzi.src = 'images/logos/partners/general-floor-logo.png';
img_msrzi.setAttribute(`alt`, `general-floor`);
img_msrzi.setAttribute(`title`, `General-floor`);
a_qSAhv.appendChild(img_msrzi);
const a_JaOya = document.createElement('a');
a_JaOya.classList.add('option');
a_JaOya.href = 'https://www.bouwpuntdeckers.be';
a_JaOya.setAttribute(`target`, `blink`);
div_xAiyz.appendChild(a_JaOya);
const img_bUkPT = new Image();
img_bUkPT.src = 'images/logos/partners/bouwpuntdeckers.png';
img_bUkPT.setAttribute(`alt`, `bouwpuntdeckers`);
img_bUkPT.setAttribute(`title`, `Bouwpunt Deckers`);
a_JaOya.appendChild(img_bUkPT);
const span_zBDnu = document.createElement('span');
span_zBDnu.classList.add('separator');
div_YcNnX.appendChild(span_zBDnu);
const a_DqQRj = document.createElement('a');
a_DqQRj.classList.add('topbar-contact-link');
a_DqQRj.href = 'form.html';
div_YcNnX.appendChild(a_DqQRj);
a_DqQRj.textContent += `Contact`;
const div_NtMrn = document.createElement('div');
div_NtMrn.classList.add('flex-container');
div_wWKlq.appendChild(div_NtMrn);
const div_yPRHg = document.createElement('div');
div_yPRHg.classList.add('socials');
div_NtMrn.appendChild(div_yPRHg);
const ul_eICCl = document.createElement('ul');
div_yPRHg.appendChild(ul_eICCl);
const li_cIPge = document.createElement('li');
ul_eICCl.appendChild(li_cIPge);
const a_fQWWi = document.createElement('a');
a_fQWWi.classList.add('ti-facebook');
a_fQWWi.href = 'https://www.facebook.com/GGFloorsConstruct';
li_cIPge.appendChild(a_fQWWi);
const li_qwvnM = document.createElement('li');
ul_eICCl.appendChild(li_qwvnM);
const a_HDYyo = document.createElement('a');
a_HDYyo.classList.add('ti-linkedin');
a_HDYyo.href = 'https://www.linkedin.com/company/ggvloerbekleding';
li_qwvnM.appendChild(a_HDYyo);
const li_oRnZW = document.createElement('li');
ul_eICCl.appendChild(li_oRnZW);
const a_cOFvH = document.createElement('a');
a_cOFvH.classList.add('ti-instagram');
a_cOFvH.href = 'https://www.instagram.com/gg_floors_constructions';
li_oRnZW.appendChild(a_cOFvH);
const div_WHGHI = document.createElement('div');
div_WHGHI.classList.add('dropdown-list', 'available-languages');
div_NtMrn.appendChild(div_WHGHI);
const div_dwMxO = document.createElement('div');
div_dwMxO.classList.add('dropdown-select');
div_WHGHI.appendChild(div_dwMxO);
const div_VyADg = document.createElement('div');
div_VyADg.classList.add('dropdown-title', 'current-lang');
div_dwMxO.appendChild(div_VyADg);
const span_gjZQq = document.createElement('span');
div_VyADg.appendChild(span_gjZQq);
span_gjZQq.textContent += `NL`;
const div_pumLj = document.createElement('div');
div_pumLj.classList.add('arrow');
div_VyADg.appendChild(div_pumLj);
const ul_lXcWI = document.createElement('ul');
ul_lXcWI.classList.add('options', 'options-lang');
div_dwMxO.appendChild(ul_lXcWI);
const li_RapCf = document.createElement('li');
li_RapCf.classList.add('option', 'selected');
ul_lXcWI.appendChild(li_RapCf);
const a_HofcW = document.createElement('a');
a_HofcW.href = '#nl';
li_RapCf.appendChild(a_HofcW);
a_HofcW.textContent += `NL`;
const li_hzYnE = document.createElement('li');
li_hzYnE.classList.add('option');
ul_lXcWI.appendChild(li_hzYnE);
const a_NdnSp = document.createElement('a');
a_NdnSp.href = '#en';
li_hzYnE.appendChild(a_NdnSp);
a_NdnSp.textContent += `EN`;
const li_kAdHW = document.createElement('li');
li_kAdHW.classList.add('option');
ul_lXcWI.appendChild(li_kAdHW);
const a_KUMZL = document.createElement('a');
a_KUMZL.href = '#de';
li_kAdHW.appendChild(a_KUMZL);
a_KUMZL.textContent += `DE`;
const li_lBsgc = document.createElement('li');
li_lBsgc.classList.add('option');
ul_lXcWI.appendChild(li_lBsgc);
const a_EXEha = document.createElement('a');
a_EXEha.href = '#fr';
li_lBsgc.appendChild(a_EXEha);
a_EXEha.textContent += `FR`;
const div_FLaGF = document.createElement('div');
div_FLaGF.classList.add('navbar');
header.appendChild(div_FLaGF);
const div_NNNYC = document.createElement('div');
div_NNNYC.classList.add('header-logo');
div_FLaGF.appendChild(div_NNNYC);
const a_MDKSA = document.createElement('a');
a_MDKSA.classList.add('link-to-home');
a_MDKSA.href = 'https://ggfloors-construct.be';
a_MDKSA.setAttribute(`target`, `_blank`);
a_MDKSA.setAttribute(`rel`, `noopener`);
a_MDKSA.setAttribute(`title`, `GG FLOORS & CONSTRUCT | Home page`);
div_NNNYC.appendChild(a_MDKSA);
const div_OVMIC = document.createElement('div');
div_OVMIC.classList.add('header-logo-image');
a_MDKSA.appendChild(div_OVMIC);
const img_PcUkZ = new Image();
img_PcUkZ.src = 'images/logos/logo.svg';
img_PcUkZ.setAttribute(`alt`, `gg-construct logo`);
div_OVMIC.appendChild(img_PcUkZ);
const span_SYYfu = document.createElement('span');
span_SYYfu.classList.add('logo-title');
a_MDKSA.appendChild(span_SYYfu);
span_SYYfu.textContent += `GG FLOORS & CONSTRUCT`;
const nav_QjVlV = document.createElement('nav');
nav_QjVlV.classList.add('topnav');
div_FLaGF.appendChild(nav_QjVlV);
const ul_hUyrY = document.createElement('ul');
nav_QjVlV.appendChild(ul_hUyrY);
const li_OXJmb = document.createElement('li');
li_OXJmb.classList.add('topnav-item');
ul_hUyrY.appendChild(li_OXJmb);
const a_wacDA = document.createElement('a');
a_wacDA.classList.add('parent-link');
a_wacDA.href = 'home.html';
li_OXJmb.appendChild(a_wacDA);
a_wacDA.textContent += `Home`;
const li_rlrBI = document.createElement('li');
li_rlrBI.classList.add('topnav-item');
ul_hUyrY.appendChild(li_rlrBI);
const a_dCaXf = document.createElement('a');
a_dCaXf.classList.add('parent-link');
a_dCaXf.href = '';
li_rlrBI.appendChild(a_dCaXf);
a_dCaXf.textContent += `Over ons`;
const li_SwIRf = document.createElement('li');
li_SwIRf.classList.add('topnav-item', 'parent');
ul_hUyrY.appendChild(li_SwIRf);
const a_EHJrQ = document.createElement('a');
a_EHJrQ.classList.add('parent-link');
a_EHJrQ.href = '';
li_SwIRf.appendChild(a_EHJrQ);
a_EHJrQ.textContent += `Activiteiten`;
const ul_hcqEy = document.createElement('ul');
ul_hcqEy.classList.add('topnav-dropdown-column');
li_SwIRf.appendChild(ul_hcqEy);
const li_aMvZb = document.createElement('li');
ul_hcqEy.appendChild(li_aMvZb);
const a_aumDq = document.createElement('a');
a_aumDq.href = '';
li_aMvZb.appendChild(a_aumDq);
a_aumDq.textContent += `Vloerder`;
const li_swQrL = document.createElement('li');
ul_hcqEy.appendChild(li_swQrL);
const a_fBFxH = document.createElement('a');
a_fBFxH.href = '';
li_swQrL.appendChild(a_fBFxH);
a_fBFxH.textContent += `Schilderwerken`;
const li_SciMV = document.createElement('li');
ul_hcqEy.appendChild(li_SciMV);
const a_YsnpK = document.createElement('a');
a_YsnpK.href = '';
li_SciMV.appendChild(a_YsnpK);
a_YsnpK.textContent += `Gyprocwerken`;
const li_DODyv = document.createElement('li');
ul_hcqEy.appendChild(li_DODyv);
const a_vMNjb = document.createElement('a');
a_vMNjb.href = '';
li_DODyv.appendChild(a_vMNjb);
a_vMNjb.textContent += `Pleisterwerken`;
const li_BCEyA = document.createElement('li');
ul_hcqEy.appendChild(li_BCEyA);
const a_EiKma = document.createElement('a');
a_EiKma.href = '';
li_BCEyA.appendChild(a_EiKma);
a_EiKma.textContent += `Terrassen en opritten`;
const li_Uopsa = document.createElement('li');
ul_hcqEy.appendChild(li_Uopsa);
const a_OUkcS = document.createElement('a');
a_OUkcS.href = '';
li_Uopsa.appendChild(a_OUkcS);
a_OUkcS.textContent += `Dakwerken`;
const li_dSBde = document.createElement('li');
ul_hcqEy.appendChild(li_dSBde);
const a_bNtgp = document.createElement('a');
a_bNtgp.href = '';
li_dSBde.appendChild(a_bNtgp);
a_bNtgp.textContent += `Gevels`;
const li_zuyhE = document.createElement('li');
ul_hcqEy.appendChild(li_zuyhE);
const a_gnIfM = document.createElement('a');
a_gnIfM.href = '';
li_zuyhE.appendChild(a_gnIfM);
a_gnIfM.textContent += `Renovatie`;
const li_FMKzn = document.createElement('li');
ul_hcqEy.appendChild(li_FMKzn);
const a_niynD = document.createElement('a');
a_niynD.href = '';
li_FMKzn.appendChild(a_niynD);
a_niynD.textContent += `Nieuwbouw`;
const li_jkdtW = document.createElement('li');
ul_hcqEy.appendChild(li_jkdtW);
const a_gOAFx = document.createElement('a');
a_gOAFx.classList.add('more', 'topnav-dropdown-item');
a_gOAFx.href = 'activiteiten.html';
li_jkdtW.appendChild(a_gOAFx);
a_gOAFx.textContent += `...`;
const li_aQlgh = document.createElement('li');
li_aQlgh.classList.add('topnav-item');
ul_hUyrY.appendChild(li_aQlgh);
const a_DkIor = document.createElement('a');
a_DkIor.classList.add('parent-link');
a_DkIor.href = '';
li_aQlgh.appendChild(a_DkIor);
a_DkIor.textContent += `Referenties`;
const li_iFCTd = document.createElement('li');
li_iFCTd.classList.add('topnav-item');
ul_hUyrY.appendChild(li_iFCTd);
const a_rJEdX = document.createElement('a');
a_rJEdX.classList.add('parent-link');
a_rJEdX.href = '';
li_iFCTd.appendChild(a_rJEdX);
a_rJEdX.textContent += `Nieuws`;
const li_NbKCY = document.createElement('li');
li_NbKCY.classList.add('topnav-item');
ul_hUyrY.appendChild(li_NbKCY);
const a_rkNdV = document.createElement('a');
a_rkNdV.classList.add('parent-link');
a_rkNdV.href = '';
li_NbKCY.appendChild(a_rkNdV);
a_rkNdV.textContent += `Vacatures`;
const li_iguxn = document.createElement('li');
li_iguxn.classList.add('topnav-item');
ul_hUyrY.appendChild(li_iguxn);
const a_FXdKb = document.createElement('a');
a_FXdKb.classList.add('parent-link');
a_FXdKb.href = 'contact.html';
li_iguxn.appendChild(a_FXdKb);
a_FXdKb.textContent += `Contact`;
const div_HaQVF = document.createElement('div');
div_HaQVF.classList.add('topnav-btns');
nav_QjVlV.appendChild(div_HaQVF);
const a_tAIBK = document.createElement('a');
a_tAIBK.classList.add('btn', 'btn-default', 'btn-call');
a_tAIBK.href = 'tel:+32472815575';
div_HaQVF.appendChild(a_tAIBK);
const img_dTNRZ = new Image();
img_dTNRZ.src = 'images/icons/phone-call.svg';
img_dTNRZ.setAttribute(`alt`, `phone`);
a_tAIBK.appendChild(img_dTNRZ);
const img_SuhbB = new Image();
img_SuhbB.src = 'images/icons/dial-pad.svg';
img_SuhbB.setAttribute(`alt`, `dial-pad`);
a_tAIBK.appendChild(img_SuhbB);
const button_lPXLu = document.createElement('button');
button_lPXLu.classList.add('btn', 'btn-search', 'ti-search');
div_HaQVF.appendChild(button_lPXLu);
const div_tIIXf = document.createElement('div');
div_tIIXf.id = 'menuToggle';
header.appendChild(div_tIIXf);
const input_HzJvt = document.createElement('input');
input_HzJvt.setAttribute(`type`, `checkbox`);
div_tIIXf.appendChild(input_HzJvt);
const span_UsqZD = document.createElement('span');
div_tIIXf.appendChild(span_UsqZD);
const span_ctJyD = document.createElement('span');
div_tIIXf.appendChild(span_ctJyD);
const span_BNKdM = document.createElement('span');
div_tIIXf.appendChild(span_BNKdM);
const ul_YMKVb = document.createElement('ul');
ul_YMKVb.classList.add('mobile-dropdown-column');
div_tIIXf.appendChild(ul_YMKVb);
const div_qdYMt = document.createElement('div');
div_qdYMt.classList.add('search');
header.appendChild(div_qdYMt);
const div_lpRMx = document.createElement('div');
div_lpRMx.classList.add('search-modal');
div_qdYMt.appendChild(div_lpRMx);
const div_MUFAM = document.createElement('div');
div_MUFAM.classList.add('search_container');
div_lpRMx.appendChild(div_MUFAM);
const div_tZPFJ = document.createElement('div');
div_tZPFJ.classList.add('search_intro-placeholder');
div_MUFAM.appendChild(div_tZPFJ);
const div_iMEqS = document.createElement('div');
div_iMEqS.classList.add('search_intro');
div_tZPFJ.appendChild(div_iMEqS);
div_iMEqS.textContent += `What are you looking for?`;
const form_aOeIi = document.createElement('form');
form_aOeIi.id = 'formMenuSearch';
form_aOeIi.setAttribute(`name`, `query`);
form_aOeIi.setAttribute(`action`, ``);
form_aOeIi.setAttribute(`method`, `GET`);
div_MUFAM.appendChild(form_aOeIi);
const div_IonOF = document.createElement('div');
div_IonOF.classList.add('search_input');
form_aOeIi.appendChild(div_IonOF);
const div_cDnjQ = document.createElement('div');
div_cDnjQ.classList.add('search-wrapper');
div_IonOF.appendChild(div_cDnjQ);
const input_CgXDq = document.createElement('input');
input_CgXDq.classList.add('search-box');
input_CgXDq.setAttribute(`type`, `search`);
input_CgXDq.setAttribute(`placeholder`, `Plaster`);
input_CgXDq.setAttribute('autofocus', '');
div_cDnjQ.appendChild(input_CgXDq);
const div_HgkLD = document.createElement('div');
div_HgkLD.classList.add('search_submit');
div_IonOF.appendChild(div_HgkLD);
const button_YeRLN = document.createElement('button');
button_YeRLN.classList.add('btn-default');
button_YeRLN.setAttribute(`type`, `submit`);
div_HgkLD.appendChild(button_YeRLN);
const img_dZkbO = new Image();
img_dZkbO.src = 'images/icons/loupe.svg';
img_dZkbO.setAttribute(`alt`, `search`);
button_YeRLN.appendChild(img_dZkbO);
const div_xTLTk = document.createElement('div');
div_xTLTk.classList.add('search_placeholder-suggestions');
div_lpRMx.appendChild(div_xTLTk);
const div_QyXJH = document.createElement('div');
div_QyXJH.classList.add('search_wrapper-suggestions');
div_xTLTk.appendChild(div_QyXJH);
const span_bovte = document.createElement('span');
div_QyXJH.appendChild(span_bovte);
const ul_emnXj = document.createElement('ul');
ul_emnXj.classList.add('search_list-suggestions');
div_QyXJH.appendChild(ul_emnXj);
const li_mJdwx = document.createElement('li');
ul_emnXj.appendChild(li_mJdwx);
const a_qravQ = document.createElement('a');
a_qravQ.classList.add('search_link');
a_qravQ.href = 'activiteiten.html';
li_mJdwx.appendChild(a_qravQ);
a_qravQ.textContent += `Plaster`;
const span_VTLBx = document.createElement('span');
li_mJdwx.appendChild(span_VTLBx);
span_VTLBx.textContent += `|`;
const li_rnZjW = document.createElement('li');
ul_emnXj.appendChild(li_rnZjW);
const a_vdTIz = document.createElement('a');
a_vdTIz.classList.add('search_link');
a_vdTIz.href = 'activiteiten.html';
li_rnZjW.appendChild(a_vdTIz);
a_vdTIz.textContent += `Ground`;
const span_mHfwC = document.createElement('span');
li_rnZjW.appendChild(span_mHfwC);
span_mHfwC.textContent += `|`;
const li_nDbnf = document.createElement('li');
ul_emnXj.appendChild(li_nDbnf);
const a_tigmn = document.createElement('a');
a_tigmn.classList.add('search_link');
a_tigmn.href = 'activiteiten.html';
li_nDbnf.appendChild(a_tigmn);
a_tigmn.textContent += `Walls`;
const span_JgAas = document.createElement('span');
li_nDbnf.appendChild(span_JgAas);
span_JgAas.textContent += `|`;
const li_myjfH = document.createElement('li');
ul_emnXj.appendChild(li_myjfH);
const a_LRfyP = document.createElement('a');
a_LRfyP.classList.add('search_link');
a_LRfyP.href = 'activiteiten.html';
li_myjfH.appendChild(a_LRfyP);
a_LRfyP.textContent += `Paint`;

const footer = document.querySelector('.footer');
const nav_yiahn = document.createElement('nav');
nav_yiahn.classList.add('footnav');
footer.appendChild(nav_yiahn);
const div_eHlht = document.createElement('div');
div_eHlht.classList.add('footnav-column');
nav_yiahn.appendChild(div_eHlht);
const h4_tMgAf = document.createElement('h4');
h4_tMgAf.classList.add('column-title');
div_eHlht.appendChild(h4_tMgAf);
h4_tMgAf.textContent += `Hoofd`;
const hr_YVtHL = document.createElement('hr');
hr_YVtHL.classList.add('title-underline');
div_eHlht.appendChild(hr_YVtHL);
const ul_XLbpz = document.createElement('ul');
div_eHlht.appendChild(ul_XLbpz);
const div_FuQNf = document.createElement('div');
div_FuQNf.classList.add('footnav-column');
nav_yiahn.appendChild(div_FuQNf);
const h4_CUnbe = document.createElement('h4');
h4_CUnbe.classList.add('column-title');
div_FuQNf.appendChild(h4_CUnbe);
h4_CUnbe.textContent += `Activiteiten`;
const hr_snsce = document.createElement('hr');
hr_snsce.classList.add('title-underline');
div_FuQNf.appendChild(hr_snsce);
const ul_zlmJt = document.createElement('ul');
div_FuQNf.appendChild(ul_zlmJt);
const div_cAtOm = document.createElement('div');
div_cAtOm.classList.add('footnav-column');
nav_yiahn.appendChild(div_cAtOm);
const h4_IVnfi = document.createElement('h4');
h4_IVnfi.classList.add('column-title');
div_cAtOm.appendChild(h4_IVnfi);
h4_IVnfi.textContent += `Socials`;
const hr_rFOEG = document.createElement('hr');
hr_rFOEG.classList.add('title-underline');
div_cAtOm.appendChild(hr_rFOEG);
const ul_ADLIH = document.createElement('ul');
div_cAtOm.appendChild(ul_ADLIH);
const li_sUsIJ = document.createElement('li');
li_sUsIJ.classList.add('footnav-link-item');
ul_ADLIH.appendChild(li_sUsIJ);
const a_EsNaW = document.createElement('a');
a_EsNaW.href = 'https://www.facebook.com/GGFloorsConstruct';
li_sUsIJ.appendChild(a_EsNaW);
a_EsNaW.textContent += `Facebook`;
const li_zXYjH = document.createElement('li');
li_zXYjH.classList.add('footnav-link-item');
ul_ADLIH.appendChild(li_zXYjH);
const a_qkqaQ = document.createElement('a');
a_qkqaQ.href = 'https://www.instagram.com/gg_floors_constructions';
li_zXYjH.appendChild(a_qkqaQ);
a_qkqaQ.textContent += `Instagram`;
const li_PPkiX = document.createElement('li');
li_PPkiX.classList.add('footnav-link-item');
ul_ADLIH.appendChild(li_PPkiX);
const a_vLzbe = document.createElement('a');
a_vLzbe.href = 'https://www.linkedin.com/company/ggvloerbekleding';
li_PPkiX.appendChild(a_vLzbe);
a_vLzbe.textContent += `Linkedin`;
const div_UZxIg = document.createElement('div');
div_UZxIg.classList.add('footnav-column', 'gegevens');
nav_yiahn.appendChild(div_UZxIg);
const h4_NBxtZ = document.createElement('h4');
h4_NBxtZ.classList.add('column-title');
div_UZxIg.appendChild(h4_NBxtZ);
h4_NBxtZ.textContent += `Gegevens:`;
const hr_BkyRr = document.createElement('hr');
hr_BkyRr.classList.add('title-underline');
div_UZxIg.appendChild(hr_BkyRr);
const ul_DVTvo = document.createElement('ul');
div_UZxIg.appendChild(ul_DVTvo);
const li_Mifmk = document.createElement('li');
li_Mifmk.classList.add('gegevens-link-item');
ul_DVTvo.appendChild(li_Mifmk);
const a_GbfGa = document.createElement('a');
a_GbfGa.href = '';
a_GbfGa.setAttribute(`target`, `_self`);
li_Mifmk.appendChild(a_GbfGa);
const span_GxOli = document.createElement('span');
span_GxOli.classList.add('ti-briefcase');
a_GbfGa.appendChild(span_GxOli);
span_GxOli.innerHTML += `&#160;`;
a_GbfGa.textContent += `GG FLOORS & CONSTRUCT bv`;
const br_rTdsZ = document.createElement('br');
a_GbfGa.appendChild(br_rTdsZ);
a_GbfGa.textContent += `BTW: BE 0704678967`;
const li_GkErs = document.createElement('li');
li_GkErs.classList.add('gegevens-link-item', 'footnav-link-item');
ul_DVTvo.appendChild(li_GkErs);
const a_MQjdp = document.createElement('a');
a_MQjdp.href = 'https://www.google.com/maps/place/GGVloerbekleding+bvba/@51.0532724,5.7378526,15z/data=!4m5!3m4!1s0x0:0xa831bc10b126f764!8m2!3d51.0532724!4d5.7378526';
a_MQjdp.setAttribute(`target`, `_self`);
li_GkErs.appendChild(a_MQjdp);
const span_mKSsa = document.createElement('span');
span_mKSsa.classList.add('ti-location-arrow');
a_MQjdp.appendChild(span_mKSsa);
span_mKSsa.innerHTML += `&#160;`;
a_MQjdp.textContent += `Kloosterpark 3, B 3650 Dilsen-Stokkem`;
const li_YWzxp = document.createElement('li');
li_YWzxp.classList.add('gegevens-link-item', 'footnav-link-item');
ul_DVTvo.appendChild(li_YWzxp);
const a_zZRql = document.createElement('a');
a_zZRql.href = 'tel:+32472815575';
a_zZRql.setAttribute(`target`, `_self`);
li_YWzxp.appendChild(a_zZRql);
const span_mgWeJ = document.createElement('span');
span_mgWeJ.classList.add('ti-mobile');
a_zZRql.appendChild(span_mgWeJ);
span_mgWeJ.innerHTML += `&#160;`;
a_zZRql.textContent += `+32472815575`;
const a_lqHDm = document.createElement('a');
a_lqHDm.href = 'mailto:ggfloorsconstruct@gmail.com';
a_lqHDm.setAttribute(`target`, `_self`);
li_YWzxp.appendChild(a_lqHDm);
const span_UxXCo = document.createElement('span');
span_UxXCo.classList.add('ti-email');
a_lqHDm.appendChild(span_UxXCo);
span_UxXCo.innerHTML += `&#160;`;
a_lqHDm.textContent += `ggfloorsconstruct@gmail.com`;
const li_lWYLq = document.createElement('li');
li_lWYLq.classList.add('gegevens-link-item');
ul_DVTvo.appendChild(li_lWYLq);
const a_rlzqw = document.createElement('a');
a_rlzqw.href = '';
a_rlzqw.setAttribute(`target`, `_self`);
li_lWYLq.appendChild(a_rlzqw);
const span_KkpRp = document.createElement('span');
span_KkpRp.classList.add('ti-wallet');
a_rlzqw.appendChild(span_KkpRp);
span_KkpRp.innerHTML += `&#160;`;
a_rlzqw.textContent += `BNP PARIBAS/Fortis`;
const br_XxNKi = document.createElement('br');
a_rlzqw.appendChild(br_XxNKi);
a_rlzqw.textContent += `BE71 0019 0088 6869`;
const img_pOYbM = new Image();
img_pOYbM.classList.add('footer-logo');
img_pOYbM.style.margin = '20px auto';
img_pOYbM.style.display = 'block';
img_pOYbM.setAttribute(`width`, `40`);
img_pOYbM.src = 'images/logo.svg';
img_pOYbM.setAttribute(`alt`, `GG Floors and Construct`);
div_UZxIg.appendChild(img_pOYbM);
const div_jkKHb = document.createElement('div');
div_jkKHb.classList.add('basement');
footer.appendChild(div_jkKHb);
const div_AoYCw = document.createElement('div');
div_AoYCw.classList.add('copyright');
div_jkKHb.appendChild(div_AoYCw);
const span_VRVLK = document.createElement('span');
span_VRVLK.classList.add('copyright-title');
div_AoYCw.appendChild(span_VRVLK);
span_VRVLK.textContent += `GG Floors & Construct 2021 ©`;
const ul_iWqoA = document.createElement('ul');
ul_iWqoA.classList.add('items-list-inline');
div_AoYCw.appendChild(ul_iWqoA);
const li_boiyO = document.createElement('li');
ul_iWqoA.appendChild(li_boiyO);
const a_KuXaU = document.createElement('a');
a_KuXaU.setAttribute(`target`, `blink`);
a_KuXaU.href = 'files/maatschappelijke-zetel.pdf';
li_boiyO.appendChild(a_KuXaU);
const span_tKhRS = document.createElement('span');
a_KuXaU.appendChild(span_tKhRS);
span_tKhRS.textContent += `Maatschappelijke Zetel`;
const li_bShHv = document.createElement('li');
ul_iWqoA.appendChild(li_bShHv);
const a_XHnxy = document.createElement('a');
a_XHnxy.setAttribute(`target`, `blink`);
a_XHnxy.href = 'files/rubriek-oprichting.pdf';
li_bShHv.appendChild(a_XHnxy);
const span_ZdLMk = document.createElement('span');
a_XHnxy.appendChild(span_ZdLMk);
span_ZdLMk.textContent += `Rubriek Oprichting`;
const li_nwQuV = document.createElement('li');
ul_iWqoA.appendChild(li_nwQuV);
const a_uNjIL = document.createElement('a');
a_uNjIL.setAttribute(`target`, `blink`);
a_uNjIL.href = 'files/financiele-gegevens.pdf';
li_nwQuV.appendChild(a_uNjIL);
const span_GMiin = document.createElement('span');
a_uNjIL.appendChild(span_GMiin);
span_GMiin.textContent += `Financiële Gegevens`;
const div_XyScq = document.createElement('div');
div_XyScq.classList.add('socials');
div_jkKHb.appendChild(div_XyScq);
const ul_csLXc = document.createElement('ul');
div_XyScq.appendChild(ul_csLXc);
const li_krpZI = document.createElement('li');
ul_csLXc.appendChild(li_krpZI);
const a_MYalv = document.createElement('a');
a_MYalv.classList.add('ti-facebook');
a_MYalv.href = 'https://www.facebook.com/GGFloorsConstruct';
li_krpZI.appendChild(a_MYalv);
const li_QVMRi = document.createElement('li');
ul_csLXc.appendChild(li_QVMRi);
const a_yoDfW = document.createElement('a');
a_yoDfW.classList.add('ti-linkedin');
a_yoDfW.href = 'https://www.linkedin.com/company/ggvloerbekleding';
li_QVMRi.appendChild(a_yoDfW);
const li_ifDPm = document.createElement('li');
ul_csLXc.appendChild(li_ifDPm);
const a_BAVIH = document.createElement('a');
a_BAVIH.classList.add('ti-instagram');
a_BAVIH.href = 'https://www.instagram.com/gg_floors_constructions';
li_ifDPm.appendChild(a_BAVIH);
const div_IQyog = document.createElement('div');
div_IQyog.classList.add('contact-widget');
footer.appendChild(div_IQyog);
const input_rpkdF = document.createElement('input');
input_rpkdF.classList.add('contact-widget-input');
input_rpkdF.setAttribute(`type`, `checkbox`);
div_IQyog.appendChild(input_rpkdF);
const button_hqlQG = document.createElement('button');
button_hqlQG.classList.add('contact-widget-btn', 'ti-comment');
div_IQyog.appendChild(button_hqlQG);
const div_PdaqZ = document.createElement('div');
div_PdaqZ.classList.add('contact-widget-container');
div_IQyog.appendChild(div_PdaqZ);
const ul_JgRLS = document.createElement('ul');
ul_JgRLS.classList.add('items-of-contact');
div_PdaqZ.appendChild(ul_JgRLS);
const li_dMRgc = document.createElement('li');
li_dMRgc.classList.add('item-phone');
ul_JgRLS.appendChild(li_dMRgc);
const a_eVUxo = document.createElement('a');
a_eVUxo.classList.add('ti-mobile');
a_eVUxo.href = 'contact.html';
a_eVUxo.setAttribute(`title`, `Contact`);
li_dMRgc.appendChild(a_eVUxo);
const li_FEVuP = document.createElement('li');
li_FEVuP.classList.add('item-mail');
ul_JgRLS.appendChild(li_FEVuP);
const a_uCuFu = document.createElement('a');
a_uCuFu.classList.add('ti-email');
a_uCuFu.href = 'mailto:ggfloorsconstruct@gmail.com';
a_uCuFu.setAttribute(`title`, `E-mail`);
li_FEVuP.appendChild(a_uCuFu);
const li_VFVue = document.createElement('li');
li_VFVue.classList.add('item-form');
ul_JgRLS.appendChild(li_VFVue);
const a_QYGet = document.createElement('a');
a_QYGet.classList.add('ti-view-list-alt');
a_QYGet.href = 'form.html';
a_QYGet.setAttribute(`title`, `Form`);
li_VFVue.appendChild(a_QYGet);
const div_fLsVJ = document.createElement('div');
div_fLsVJ.classList.add('chat-to');
div_IQyog.appendChild(div_fLsVJ);
const p_gMpFZ = document.createElement('p');
div_fLsVJ.appendChild(p_gMpFZ);
p_gMpFZ.textContent += `Contact us`;

let topNavItem = document.querySelectorAll('.parent-link');
let currentLang = document.querySelector('.current-lang span');
currentLang.textContent = localStorage.getItem('currentLang') || 'NL';
let lang = currentLang.textContent.toLowerCase();
const footNavColumn = document.querySelectorAll('.footnav-column ul');
const mobileDropdownColumn = document.querySelector('.mobile-dropdown-column');
const topNavDropdownColumnLink = document.querySelectorAll('.topnav-dropdown-column a');
const searchIntro = document.querySelector('.search_intro');
const partners = document.querySelector('.partners span');
const topbarContactLink = document.querySelector('.topbar-contact-link');
const searchLink = document.querySelectorAll('.search_link');
const searchBox = document.querySelector('.search-box');
const footNavColumnTitle = document.querySelectorAll('.footnav-column h4')

let getNav = () => {
  for (let i = 0; i < topNavItem.length; i++) {
    topNavItem[i].textContent = data[lang][0][i][0];
    topNavItem[i].href = `${data.nl[0][i][0].replace(/ /g, '-').toLowerCase()}.html`;

    const li_HVtWm = document.createElement('li');
    li_HVtWm.classList.add('footnav-link-item');
    footNavColumn[0].appendChild(li_HVtWm);
    const a_mLBgC = document.createElement('a');
    a_mLBgC.href = `${data.nl[0][i][0].replace(/ /g, '-').toLowerCase()}.html`;
    li_HVtWm.appendChild(a_mLBgC);
    a_mLBgC.textContent += data[lang][0][i][0];

    const li_UwhqJ = document.createElement('li');
    mobileDropdownColumn.appendChild(li_UwhqJ);
    const a_Zgcgk = document.createElement('a');
    li_UwhqJ.appendChild(a_Zgcgk);
    a_Zgcgk.href = `${data.nl[0][i][0].replace(/ /g, '-').toLowerCase()}.html`;
    a_Zgcgk.textContent += data[lang][0][i][0];
  }

  for (let i = 0; i < data[lang][0][2][1].length - 1; i++) {
    const li_HVtW = document.createElement('li');
    li_HVtW.classList.add('footnav-link-item');
    footNavColumn[1].appendChild(li_HVtW);
    const a_mLBg = document.createElement('a');
    a_mLBg.href = `${data.nl[0][2][1][i][0].replace(/ /g, '-').toLowerCase()}.html`;
    li_HVtW.appendChild(a_mLBg);
    a_mLBg.textContent += data[lang][0][2][1][i][0];
  }

  for (let j = 0; j < data[lang][0][2][1].length; j++) {
    topNavDropdownColumnLink[j].textContent = data[lang][0][2][1][j][0];
    topNavDropdownColumnLink[j].href = `${data.nl[0][2][1][j][0].replace(/ /g, '-').toLowerCase()}.html`;
  }

  topNavDropdownColumnLink[topNavDropdownColumnLink.length - 1].href = 'activiteiten.html';

  for (let i = 0; i < searchLink.length; i++) {
    searchLink[i].textContent = data[lang][6][i + 1];
  }

  searchIntro.textContent = data[lang][6][0];
  searchBox.setAttribute('placeholder', data[lang][6][1])
  partners.textContent = data[lang][1];
  topbarContactLink.textContent = data[lang][2];
  footNavColumnTitle[0].textContent = data[lang][8];
  footNavColumnTitle[1].textContent = data[lang][0][2][0];
  footNavColumnTitle[3].textContent = data[lang][9];
}

window.addEventListener('hashchange', function (e) {
  mobileDropdownColumn.innerHTML = ``;
  footNavColumn[0].innerHTML = ``;
  footNavColumn[1].innerHTML = ``;
  setTimeout(() => {
    lang = currentLang.textContent.toLowerCase();
    getNav();
  }, 0)
});

getNav();
